import {readFile,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {extractPage} from '../scripts/extract.mjs';
import {finalizeBackgrounds} from '../scripts/characters-parser.mjs';
import {compareCards} from './card-comparison.mjs';
import {validateBackgrounds} from '../../fvtt-crows-system/module/character-creation.mjs';
const baseURL=pathToFileURL(process.env.FOUNDRY_PDFJS??'C:/Program Files/Foundry Virtual Tabletop/resources/app/node_modules/@foundryvtt/pdfjs/').href;
const pdfjs=await import(new URL('build/pdf.mjs',baseURL));pdfjs.GlobalWorkerOptions.workerSrc=new URL('build/pdf.worker.mjs',baseURL).href;
const expected=JSON.parse(await readFile(new URL('../out/characters-baseline.json',import.meta.url),'utf8'));
const cards=JSON.parse(await readFile(new URL('../out/cards-baseline.json',import.meta.url),'utf8')).flatMap(c=>c.expected);
const result=await extractPage(new Uint8Array(await readFile(expected.file)),null,'characters',{pdfjs,baseURL,source:'characters'});
const traitFields=items=>items.map(item=>({name:item.name,type:item.type,system:{...item.system,description:item.system.description.replaceAll('&#39;',"'").replaceAll('&quot;','"')}}));
const backgrounds=finalizeBackgrounds(result.characterData,cards);
validateBackgrounds(backgrounds);
const differences={backgrounds:compareCards(expected.backgrounds,backgrounds),common:compareCards(expected.common,result.characterData.common),connections:compareCards(expected.connections,result.characterData.connections),traits:compareCards(traitFields(expected.traits),traitFields(result.documents))};
const summary={backgrounds:backgrounds.length,connections:result.characterData.connections.length,traits:result.documents.length,differences:Object.fromEntries(Object.entries(differences).map(([key,value])=>[key,value.length]))};
await writeFile(new URL('../out/characters-comparison.json',import.meta.url),JSON.stringify({summary,differences},null,2));
console.log(summary);for(const [key,value] of Object.entries(differences))if(value.length)console.log(key,value.slice(0,8));
if(Object.values(differences).some(list=>list.length))process.exitCode=1;
