// Foundry core icon paths, matching the existing system importer.
export const animalIcons={
  "Ape": "icons/creatures/magical/humanoid-giant-forest-blue.webp",
  "Bear": "icons/creatures/abilities/bear-roar-bite-brown.webp",
  "Bear, Cave": "icons/creatures/abilities/bear-roar-bite-brown-green.webp",
  "Camel": "icons/creatures/mammals/ox-buffalo-horned-green.webp",
  "Cat": "icons/creatures/mammals/cat-hunched-glowing-red.webp",
  "Cat, Big": "icons/creatures/mammals/cat-hunched-glowing-red.webp",
  "Wildcat": "icons/creatures/mammals/cat-hunched-glowing-red.webp",
  "Chicken": "icons/creatures/birds/chicken-hen-white.webp",
  "Crocodile": "icons/creatures/reptiles/lizard-mouth-glowing-red.webp",
  "Crow": "icons/creatures/birds/birds-flock-fly-yellow.webp",
  "Crow, Giant": "icons/creatures/birds/birds-flock-fly-yellow.webp",
  "Deer": "icons/creatures/mammals/deer-antlers-green.webp",
  "Dog": "icons/creatures/mammals/dog-husky-white-blue.webp",
  "Donkey": "icons/creatures/mammals/goat-horned-blue.webp",
  "Elephant": "icons/creatures/mammals/elk-moose-marked-green.webp",
  "Goat": "icons/creatures/mammals/goat-horned-blue.webp",
  "Hawk": "icons/creatures/birds/raptor-hawk-flying.webp",
  "Horse, Draft": "icons/creatures/mammals/ox-bull-horned-glowing-orange.webp",
  "Horse, Riding": "icons/creatures/mammals/deer-movement-leap-green.webp",
  "Horse, War": "icons/creatures/mammals/bull-horned-blue.webp",
  "Monitor Lizard": "icons/creatures/reptiles/lizard-iguana-green.webp",
  "Mule": "icons/creatures/mammals/goat-horned-blue.webp",
  "Ox": "icons/creatures/mammals/ox-buffalo-horned-green.webp",
  "Rat": "icons/creatures/mammals/rodent-rat-green.webp",
  "Scorpion, Giant": "icons/creatures/invertebrates/scorpion-yellow.webp",
  "Snake, Constrictor": "icons/creatures/reptiles/snake-poised-white.webp",
  "Snake, Venomous": "icons/creatures/reptiles/snake-fangs-bite-green.webp",
  "Snake, Venomous Giant": "icons/creatures/reptiles/snake-fangs-bite-green-yellow.webp",
  "Spider": "icons/creatures/invertebrates/spider-dotted-green.webp",
  "Spider, Giant": "icons/creatures/invertebrates/spider-large-white-green.webp",
  "Wolf": "icons/creatures/mammals/wolf-howl-moon-gray.webp",
  "Wolf, Dire": "icons/creatures/mammals/wolf-shadow-black.webp"
};
